services:
  - type: web
    name: androfit-ai-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false  
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: PORT
        value: 10000
